version: '3.8'
services:
  occ:
    build: .
    image: occ:latest
    container_name: occ
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=change-me
      - DATA_DIR=/data
      - UPLOAD_FOLDER=/data/uploads
      - DATABASE_URL=sqlite:////data/occ.db
      - OFFLINE=1
    volumes:
      - occ-data:/data
      # Optional: pass through host folder with FIT files
      # - ./sample_fits:/import
    restart: unless-stopped
volumes:
  occ-data:
